export { EkgClient } from "./client.js";
export { JsonRpcError, StdioTransport, StreamTransport } from "./transport.js";
export type {
  AdaptationEvidenceRef,
  AdaptationEvidenceGate,
  AdaptationAction,
  AdaptationKnowledgeRef,
  AdaptationOutcome,
  AdaptationPlan,
  AdaptationPlanInput,
  AdaptationReconciliationEntry,
  AdaptationReconciliationPlan,
  AdaptationReconciliationReceipt,
  AdaptationReceipt,
  AdaptationRecord,
  AdaptationTarget,
  ApplyAdaptationInput,
  AttributionMechanism,
  AttributionConfidence,
  AttributionSelector,
  ClaimImplication,
  ClaimUncertainty,
  ClaimScopeAssignment,
  ConceptInput,
  Contradiction,
  ContradictionClaim,
  ContradictionRefinement,
  CreditAttribution,
  CompletedCycleProgress,
  CycleAssumption,
  CycleBudget,
  CycleInput,
  CycleProgress,
  DemonstratedFeature,
  EpisodeFilter,
  EpisodeFeedback,
  EkgClientOptions,
  FeedbackInput,
  FailureAnalysisInput,
  JsonValue,
  NeedTeacherProgress,
  ProposalProvenanceWire,
  RpcTransport,
  RecordContradictionInput,
  RefineContradictionInput,
  TeacherProposalWire,
  TeacherRequestWire,
} from "./types.js";
