[package]
name = "ekg-server"
version.workspace = true
edition.workspace = true

[dependencies]
ekg-adapt.workspace = true
ekg-core.workspace = true
ekg-engine.workspace = true
ekg-episode.workspace = true
ekg-graph.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
