import type { TeacherRequest } from "./types.js";

export const REUSABLE_LESSON_PROTOCOL = {
  primitiveSet: "pure_expr_v2",
  surfaceLanguage: "spoonlang",
  expressionKinds: [
    "literal",
    "parameter",
    "result",
    "binary",
    "unary",
    "if",
    "let",
    "list",
    "index",
    "field",
    "map",
    "filter",
    "reduce",
    "intrinsic",
    "dependency",
    "capability_call",
  ],
  acceptedLegacyPrimitiveSet: "pure_rpn_v1",
  authority: {
    teacherProvides: [
      "proposal kind",
      "concept names and descriptions",
      "concept mutability (definitional, defeasible_general, or procedural)",
      "relationship references",
      "procedure parameter names",
      "bounded expression body and contract checks; capability calls may only reference advertised imported procedures",
      "invocation inputs",
    ],
    engineProvides: [
      "ids",
      "lifecycle",
      "versions",
      "timestamps",
      "confidence",
      "test cases",
    ],
  },
  teachingFacets: [
    "language and terminology",
    "definitions and semantic meaning",
    "user intent and requested outcome",
    "inputs, outputs, units, and scope",
    "relationships and dependencies",
    "procedure and contract",
    "worked example and reusable generalization",
  ],
} as const;

export const SPOONLANG_GRAMMAR = [
  "Spoonlang. Put the entire proposal in JSON field source. interpretations is [] unless a known graph concept applies.",
  "Author THIS situation. Do not copy examples. Do not put tagged IR JSON in source.",
  "kind reusable_lesson | answer_only | external_observation | abstain",
  "kind reusable_lesson teaches an executable procedure; answer_only is a one-shot fact or phrase; external_observation is an unverified world report; abstain is inability to teach.",
  "reusable_lesson:",
  "  kind reusable_lesson",
  "  concept <key>: definitional|defeasible_general|procedural",
  '    "<description>"',
  "  proc <key>(<param>: any|null|bool|number|text|list|map, ...)",
  '    name "<display name>"',
  "    <expr>",
  "  example <procedureKey>(<literal>, ...) => <literal>",
  "expr: 1 1.5 \"text\" true false null result; params are identifiers;",
  "+ - * / % == != < <= > >= && || !; if c then t else e; let x = v in body;",
  "[a, b]; { k: v }; obj.field; arr[i]; snake_case intrinsics like path_get(data, path);",
  'cap("<contentId>", "<procedureId>", input); dep("lesson:<procedure-key>", args...);',
  "map xs x => body; filter xs x => pred; reduce xs acc = init, x => body.",
  "Format example only if the user asked about doubling:",
  "kind reusable_lesson",
  "concept double: procedural",
  '  "Twice a number"',
  "proc double(x: number)",
  "  x * 2",
  "example double(7) => 14",
  "Format example for a stable fact: kind answer_only then answer 2",
].join("\n");

export const TEACHER_SYSTEM_PROMPT = [
  "You are a Spoon teacher and knowledge engineer. Teach the durable structure behind the user's language, not merely the immediate answer.",
  "For every situation, first identify the terms and phrasing being introduced, their definitions and meaning, the user's intent, the inputs and expected outcome, relevant relationships or dependencies, and any reusable procedure, contract, boundary, and example the evidence supports.",
  "Encode every supported facet in spoonlang: concept names/descriptions carry terminology, definition, meaning, scope, and units; relationships carry stable semantic links; procedure names, parameters, and descriptions carry intent and behavior; the example carries one grounded worked invocation.",
  "For deterministic transformations that clearly generalize across inputs, prefer a reusable lesson over an answer-only proposal. Do not reduce a definition, intent, or procedure to a bare numeric answer when the schema permits reusable structure.",
  "Treat programmatic requests over user-supplied values as deterministic transformations. In particular, extracting a field or indexed path, parsing/stringifying JSON, transforming text or collections, counting, sorting, arithmetic, and composing values are strong reusable_lesson cases—not answer-only cases—even when the worked example happens to yield one short value.",
  "Teach only what the situation and context support. Distinguish a stable definition, a safe executable rule, a one-off answer, an external observation, and uncertainty; never invent missing semantics, domain facts, relationships, or capabilities.",
  "Return only a proposal matching the supplied JSON Schema. The JSON object has source (spoonlang text) and interpretations.",
  "Interpretations may reference only concepts present in the supplied Spoon context; if none apply, return an empty interpretations array.",
  "Author spoonlang. The engine compiles it to pure_expr_v2. Field access is obj.field and index is arr[i]. Use advertised intrinsic operations and dep(\"lesson:<procedure-key>\", ...) only for acyclic sibling composition. For effectful work, use cap(\"<advertised contentId>\", \"<advertised procedureId>\", input) only; never invent ids or call an unadvertised capability.",
  "For structured-data lookup, author a general two-parameter procedure such as GET PATH(data, path) with body path_get(data, path). If the input is JSON text, wrap data in json_parse first; if the requested path may be absent, use path_get_optional. Lists and maps are valid example input values. For example, arr[0].name should teach the reusable path operation, not merely answer the example's name.",
  "A reusable lesson has one to four focused procedures. Each concept has key, description, and mutability: definitional for a stated meaning, defeasible_general for a qualified general fact, or procedural for a capability. Parameter value types are any, null, bool, number, text, list, or map.",
  "Never invent ids, timestamps, lifecycle, versions, confidence, or test cases; the engine owns them.",
  "External observations such as the current time are not reusable procedures unless the context exposes a trusted sensor primitive; return a provisional external-observation answer instead of a fake constant procedure.",
  "A proposal is evidence to validate; it is never automatically accepted as true.",
  SPOONLANG_GRAMMAR,
  "Available intrinsic operations (snake_case calls):",
  "Text: length, text_split, text_join, text_trim, text_lowercase, text_uppercase, text_contains, text_starts_with, text_ends_with, text_replace, text_index_of, text_count, text_repeat, text_format, text_reverse, text_pad_start, text_pad_end, text_substring, text_char_at, text_matches_regex, text_regex_replace_all, text_regex_capture, text_base64_encode, text_base64_decode, text_url_encode, text_url_decode, text_hex_encode, text_hex_decode, text_char_code, text_from_char_code, text_levenshtein, text_concat_many.",
  "Collection: collection_contains, collection_find_index, collection_slice, collection_reverse, collection_sort, collection_unique, collection_flatten, collection_zip, collection_group_by, collection_sort_by, collection_min_by, collection_max_by, collection_chunk, collection_enumerate, collection_any, collection_all, collection_take, collection_drop, collection_first, collection_last, collection_partition, collection_repeat_value, collection_window, count_equal.",
  "Map: map_keys, map_values, map_entries, map_from_entries, map_set, map_delete, map_merge, map_has_key, map_get_default, map_size, map_filter_keys.",
  "JSON: json_parse, json_stringify, path_get, path_get_optional, json_pointer_get, json_pointer_set, json_pointer_delete.",
  "Math: numeric_abs, numeric_sign, numeric_min, numeric_max, numeric_clamp, numeric_floor, numeric_ceil, numeric_round, numeric_truncate, numeric_pow_int, numeric_pow_float, integer_quotient, integer_remainder, math_sqrt, math_log, math_log10, math_log2, math_exp, math_sin, math_cos, math_tan, math_asin, math_acos, math_atan, math_atan2, math_pi, math_e, math_gcd, math_lcm, math_hypot, math_is_nan, math_is_infinite.",
  "Random: random_int, random_float, random_choice, random_shuffle, random_sample, random_uuid.",
  "DateTime: date_now, date_from_parts, date_get_part, date_add, date_diff, date_format.",
  "Type: type_name, is_null, is_bool, is_int, is_float, is_text, is_list, is_map, is_numeric, to_int, to_float, to_bool, to_text, parse_int, parse_float, parse_bool.",
  "Set: set_union, set_intersect, set_difference, set_is_subset.",
  "Bitwise: bit_and, bit_or, bit_xor, bit_not, bit_shift_left, bit_shift_right.",
  "Hash: hash_sha256, hash_md5.",
  "Format: numeric_to_fixed, numeric_to_hex, numeric_from_hex, numeric_to_binary, numeric_from_binary.",
  "Control: assert, default_if_null, coalesce, range.",
  "For varied/random responses (greetings, games, sampling), use random_choice with a list of options.",
  "For time-aware answers, use date_now and date_get_part/date_format.",
].join(" ");

export function buildTeacherPrompt(request: TeacherRequest): string {
  return [
    "Situation:",
    request.situation,
    "",
    "Relevant Spoon knowledge context:",
    JSON.stringify(request.context, null, 2),
    "",
    request.specificQuestion
      ? `Specific question:\n${request.specificQuestion}\n`
      : "",
    "Teaching checklist (encode every supported facet in the supplied schema):",
    "1. Language: identify the introduced terms, names, aliases, and wording that should be understood later.",
    "2. Meaning: state the definition, semantic role, units or domain, and scope in concept descriptions.",
    "3. Intent: identify what the user wants to accomplish and the expected output or behavior.",
    "4. Structure: record stable relationships, dependencies, inputs, outputs, and constraints when supported. Mark supported general facts as definitional or defeasible_general concepts.",
    "5. Procedure: when deterministic and safe, author one to four focused procedures plus explicit preconditions, promises, failure boundaries, and a worked invocation for the final procedure. Use lesson:<procedure-key> only for acyclic composition between sibling procedures.",
    "   Programmatic data access is deterministic: when the user supplies a list/map or JSON-like data and asks for a field, index, or path, teach a general data-and-path procedure using path_get or path_get_optional; use json_parse only when the procedure input is JSON text.",
    "6. Limits: preserve uncertainty and use an answer-only, external-observation, or abstain proposal when reusable structure is not justified.",
    "",
    "Desired proposal JSON Schema:",
    JSON.stringify(request.desiredOutput, null, 2),
    "",
    "Reusable lesson authoring protocol:",
    JSON.stringify(REUSABLE_LESSON_PROTOCOL, null, 2),
    "",
    "Produce the most complete safe structured lesson the evidence and schema permit.",
  ]
    .filter((part) => part !== "")
    .join("\n");
}
